# Generated by Django 4.2.2 on 2023-06-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0002_alter_block_slug_block_block_block_slug_d8721f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
