# Generated by Django 4.2.2 on 2023-06-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0006_remove_blocks_slug_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocks",
            name="block_status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "system_define"), (0, "custom_define")],
                default=1,
                help_text="1 - system_define, 0 - custom_define",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blocks",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
