# Generated by Django 4.2.2 on 2023-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0007_alter_blocks_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation date"),
        ),
        migrations.AlterField(
            model_name="blocks",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "system_define"), (0, "custom_define")],
                default=1,
                help_text="1 - system_define, 0 - custom_define",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blocks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updation date"),
        ),
    ]
