# Generated by Django 4.2.2 on 2023-06-14 11:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blocks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("content", tinymce.models.HTMLField()),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Active"), (0, "Inactive")],
                        default=1,
                        help_text="1->Active, 0->Inactive",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="block_block_slug_ab4d45_idx")
                ],
            },
        ),
    ]
