# Generated by Django 4.2.2 on 2023-07-10 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blocks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("content", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Active"), (0, "Inactive")],
                        default=1,
                        help_text="1->Active, 0->Inactive",
                        null=True,
                    ),
                ),
                (
                    "block_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "system_define"), (0, "custom_define")],
                        default=1,
                        help_text="1 - system_define, 0 - custom_define",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="creation date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="updation date",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="block_block_slug_ab4d45_idx")
                ],
            },
        ),
    ]
