# Generated by Django 4.2.2 on 2023-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blocks",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("content", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Active"), (0, "Inactive")],
                        default=1,
                        help_text="1->Active, 0->Inactive",
                        null=True,
                    ),
                ),
                (
                    "block_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "system_define"), (0, "custom_define")],
                        default=1,
                        help_text="1 - system_define, 0 - custom_define",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updation date"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="block_block_slug_ab4d45_idx")
                ],
            },
        ),
    ]
