# Generated by Django 4.2.2 on 2023-06-15 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="blocks",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="updation date",
            ),
        ),
    ]
