# Generated by Django 4.2.2 on 2023-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks",
            name="block_status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "system_define"), (0, "custom_define")],
                default=1,
                help_text="1 - system_define, 0 - custom_define",
                null=True,
                verbose_name="block_status",
            ),
        ),
        migrations.AlterField(
            model_name="blocks",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="blocks",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Active"), (0, "Inactive")],
                default=1,
                help_text="1->Active, 0->Inactive",
                null=True,
                verbose_name="status",
            ),
        ),
    ]
