# Generated by Django 4.2.2 on 2023-06-14 11:20

from django.db import migrations
import static.tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks",
            name="content",
            field=static.tinymce.models.HTMLField(),
        ),
    ]
