# Generated by Django 4.2.2 on 2023-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0002_alter_blocks_created_at_alter_blocks_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
