# Generated by Django 4.2.2 on 2023-06-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0003_alter_blocks_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocks",
            name="slug_url",
            field=models.URLField(
                default="http://127.0.0.1:8000/block/render/",
                verbose_name="http://127.0.0.1:8000/block/render/<django.db.models.fields.SlugField>",
            ),
            preserve_default=False,
        ),
    ]
