# Generated by Django 4.2.2 on 2023-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0004_blocks_slug_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks", name="slug_url", field=models.URLField(default=""),
        ),
    ]
