# Generated by Django 4.2.2 on 2023-06-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CronJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("time_expression", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                ("script_path", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CronSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("execute_start_datetime", models.DateTimeField()),
                ("execute_end_datetime", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
                ("timezone", models.CharField(max_length=255)),
                ("max_retries", models.IntegerField()),
                ("retry_count", models.IntegerField()),
                ("retry_delay", models.IntegerField()),
                ("concurrency", models.IntegerField()),
                (
                    "cron_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cron.cronjob"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CronLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_time", models.DateTimeField()),
                ("status", models.BooleanField(default=False)),
                ("output", models.TextField()),
                ("error_message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "cron_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cron.cronjob"
                    ),
                ),
            ],
        ),
    ]
