# Generated by Django 4.2.2 on 2023-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cron", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronschedule",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Pending"),
                    (2, "Running"),
                    (3, "Completed"),
                    (4, "Failed"),
                ],
                default=1,
                help_text="1->Pending, 2->Running, 3->Completed, 4->Failed",
                null=True,
            ),
        ),
    ]
