# Generated by Django 4.2.2 on 2023-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cron", "0005_alter_cronlog_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronlog",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
