# Generated by Django 4.2.2 on 2023-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cron", "0006_alter_cronlog_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronschedule",
            name="execute_start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
