# Generated by Django 4.2.3 on 2023-07-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('pt', 'Português'), ('ru', 'Русский'), ('zh-hans', '简体中文'), ('zh-hant', '繁體中文'), ('ja', '日本語'), ('ko', '한국어'), ('ar', 'العربية'), ('hi', 'हिन्दी'), ('bn', 'বাংলা'), ('pa', 'ਪੰਜਾਬੀ'), ('ms', 'Bahasa Melayu'), ('id', 'Bahasa Indonesia'), ('tr', 'Türkçe'), ('vi', 'Tiếng Việt'), ('th', 'ภาษาไทย'), ('pl', 'Polski'), ('uk', 'Українська'), ('cs', 'Čeština'), ('nl', 'Nederlands'), ('hu', 'Magyar'), ('sv', 'Svenska'), ('da', 'Dansk'), ('fi', 'Suomi'), ('no', 'Norsk'), ('el', 'Ελληνικά'), ('he', 'עברית'), ('fa', 'فارسی'), ('bg', 'Български'), ('hr', 'Hrvatski'), ('lt', 'Lietuvių'), ('sk', 'Slovenčina'), ('sl', 'Slovenščina'), ('sr', 'Српски'), ('ro', 'Română'), ('eo', 'Esperanto')], max_length=10),
        ),
    ]
