# Generated by Django 4.2.2 on 2023-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0002_alter_profile_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msgid", models.CharField(max_length=200)),
                ("msgstr", models.CharField(max_length=200)),
            ],
        ),
    ]
