# Generated by Django 4.2.2 on 2023-07-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0003_translate"),
    ]

    operations = [
        migrations.DeleteModel(name="Translate",),
    ]
