# Generated by Django 4.2.2 on 2023-06-14 10:37

from django.db import migrations
import static.tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_rename_title_custompage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompage",
            name="content",
            field=static.tinymce.models.HTMLField(),
        ),
    ]
