# Generated by Django 4.2.2 on 2023-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocklog",
            name="actions",
            field=models.CharField(max_length=255, verbose_name="action"),
        ),
        migrations.AlterField(
            model_name="blocklog",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="ip address"),
        ),
        migrations.AlterField(
            model_name="pagelog",
            name="actions",
            field=models.CharField(max_length=255, verbose_name="action"),
        ),
        migrations.AlterField(
            model_name="pagelog",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="ip address"),
        ),
    ]
