# Generated by Django 4.2.2 on 2023-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_logs",
            "0002_remove_blocklog_timestamp_remove_pagelog_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelog",
            name="user",
            field=models.IntegerField(verbose_name="user"),
        ),
    ]
