# Generated by Django 4.2.2 on 2023-06-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_logs", "0003_alter_pagelog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelog",
            name="user",
            field=models.CharField(max_length=255, verbose_name="user"),
        ),
    ]
