# Generated by Django 4.2.2 on 2023-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_title_created_at_alter_title_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Active"), (0, "Inactive")],
                default=1,
                help_text="1->Active, 0->Inactive",
                null=True,
            ),
        ),
    ]
