# Generated by Django 4.2.2 on 2023-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_custompage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompage", name="content", field=models.TextField(),
        ),
    ]
