# Generated by Django 4.2.2 on 2023-07-18 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configure_SMTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.EmailField(max_length=250, verbose_name="host")),
                ("port", models.IntegerField(default=587, verbose_name="port")),
                ("username", models.CharField(max_length=250, verbose_name="username")),
                ("password", models.CharField(max_length=250, verbose_name="password")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "SMTP Configuration",
                "verbose_name_plural": "SMTP Configurations",
            },
        ),
        migrations.CreateModel(
            name="FromOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Mail_template_log",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mail_template",
                    models.CharField(max_length=250, verbose_name="mail_template"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Mail template log",
                "verbose_name_plural": "Mail template logs",
                "db_table": "mail_template_log",
            },
        ),
        migrations.CreateModel(
            name="Scheduled_mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=250, verbose_name="event")),
                (
                    "html_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="html_content"
                    ),
                ),
                ("subject", models.CharField(max_length=250, verbose_name="subject")),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, max_length=250, null=True, verbose_name="from_email"
                    ),
                ),
                (
                    "recipient_list",
                    models.TextField(
                        blank=True, null=True, verbose_name="recipient_list"
                    ),
                ),
                ("cc", models.CharField(blank=True, max_length=255)),
                ("bcc", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Scheduled Mail",
                "verbose_name_plural": "Scheduled Mails",
                "db_table": "scheduled_mail",
            },
        ),
        migrations.CreateModel(
            name="Mail_template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "code",
                    models.CharField(max_length=250, unique=True, verbose_name="code"),
                ),
                ("subject", models.CharField(max_length=250, verbose_name="subject")),
                ("body", models.TextField(blank=True, null=True, verbose_name="body")),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default=True,
                        max_length=255,
                        verbose_name="status",
                    ),
                ),
                ("other", models.BooleanField(default=False)),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, max_length=250, null=True, verbose_name="from_email"
                    ),
                ),
                ("cc", models.CharField(blank=True, max_length=255)),
                ("bcc", models.CharField(blank=True, max_length=255)),
                ("event", models.CharField(max_length=250, verbose_name="event")),
                (
                    "send_option",
                    models.CharField(
                        choices=[("cron", "Cron"), ("immediately", "Immediately")],
                        default="cron",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "from_option",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mail.fromoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail Templates",
                "verbose_name_plural": "Mail Templates",
                "db_table": "mail_template",
            },
        ),
    ]
