# Generated by Django 4.2.2 on 2023-07-28 09:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail_template",
            name="create_type",
            field=models.CharField(
                choices=[("New", "New"), ("Existing", "Existing")],
                default="New",
                max_length=12,
                verbose_name="create type",
            ),
        ),
        migrations.AlterField(
            model_name="mail_template",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
