# Generated by Django 4.2.2 on 2023-07-28 10:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_mail_template_log_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail_template",
            name="body",
            field=django_quill.fields.QuillField(),
        ),
    ]
