# Generated by Django 4.2.2 on 2023-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_mail_template_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail_template_log",
            name="action",
            field=models.CharField(
                editable=False, max_length=250, verbose_name="action"
            ),
        ),
        migrations.AlterField(
            model_name="mail_template_log",
            name="mail_template",
            field=models.CharField(
                editable=False, max_length=250, verbose_name="mail_template"
            ),
        ),
    ]
