# Generated by Django 4.2.2 on 2023-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_alter_mail_template_log_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail_template_log",
            name="action",
            field=models.CharField(max_length=250, verbose_name="action"),
        ),
        migrations.AlterField(
            model_name="mail_template_log",
            name="mail_template",
            field=models.CharField(max_length=250, verbose_name="mail_template"),
        ),
    ]
