# Generated by Django 4.2.2 on 2023-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="app_config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("store", models.IntegerField(default=0)),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
